services:
  app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: wake-time-calculator

  dev:
    image: python:3.11-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 -m http.server 8000
    container_name: wake-time-calculator-dev