services:
  app:
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: wake-time-calculator
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  dev:
    image: python:3.11-alpine
    working_dir: /app/src
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 -m http.server 8000
    container_name: wake-time-calculator-dev
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  playwright:
    image: mcr.microsoft.com/playwright:v1.55.1-jammy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CI=true
    command: npx playwright test
    depends_on:
      - dev
    network_mode: "host"
    container_name: wake-time-calculator-playwright

  playwright-visual:
    image: mcr.microsoft.com/playwright:v1.55.1-jammy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CI=false
    command: npx playwright test tests/visual
    depends_on:
      - dev
    network_mode: "host"
    container_name: wake-time-calculator-visual
