name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.json'
      - '.github/workflows/**'
  workflow_dispatch:  # Enable manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}  # Don't cancel main branch runs

jobs:
  # Sanity check: ensure developer scripts don't mask failures
  script-sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Check scripts for '|| true'
        run: |
          set -euo pipefail
          matches=$(grep -R --line-number --exclude='setup-dev.sh' -F '|| true' scripts/ || true)

          if [ -n "$matches" ]; then
            echo "$matches"
            echo "Found '|| true' in scripts/ (excluding setup-dev.sh) — this can mask failures in CI."
            exit 1
          fi

          echo "✓ No unexpected '|| true' found in scripts/"

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      # Lint, validate HTML, and run minimal unit tests
      - name: Validate code quality
        run: npm run validate:all
