name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.json'
      - '.github/workflows/**'
  workflow_dispatch:  # Enable manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}  # Don't cancel main branch runs

jobs:
  # Sanity check: ensure developer scripts don't mask failures
  script-sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Check scripts for '|| true'
        run: |
          set -euo pipefail
          matches=$(grep -R --line-number --exclude='setup-dev.sh' -F '|| true' scripts/ || true)

          if [ -n "$matches" ]; then
            echo "$matches"
            echo "Found '|| true' in scripts/ (excluding setup-dev.sh) — this can mask failures in CI."
            exit 1
          fi

          echo "✓ No unexpected '|| true' found in scripts/"

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      # Enforce pre-commit parity: same validation as husky/lint-staged
      - name: Lint, validate HTML, and run unit tests
        run: npm run validate:all

  visual-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/njrun1804/wake-time-calculator-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        HOME: /root
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      # Playwright browsers and dependencies are pre-installed in the Docker container
      # No need to install or cache them!

      - name: Run visual regression tests (shard ${{ matrix.shard }}/8)
        run: npm run test:visual -- --shard=${{ matrix.shard }}/8
        env:
          HOME: /root

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-results-${{ matrix.shard }}
          path: test-results/
          retention-days: 7

  safari-tests:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Cache Playwright WebKit
        uses: actions/cache@v4
        id: playwright-webkit-cache
        with:
          path: ~/Library/Caches/ms-playwright
          key: playwright-webkit-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: playwright-webkit-${{ runner.os }}-

      - name: Install Playwright WebKit
        if: steps.playwright-webkit-cache.outputs.cache-hit != 'true'
        run: npx playwright install webkit

      - name: Run Safari tests
        run: npm run test:ci -- --project=webkit

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: safari-test-results
          path: playwright-report/
          retention-days: 7

  pr-comment:
    runs-on: ubuntu-latest
    needs: [ validate, visual-tests, safari-tests ]
    if: |
      always() &&
      github.event_name == 'pull_request' &&
      (needs.validate.result == 'failure' ||
       needs.visual-tests.result == 'failure' ||
       needs.safari-tests.result == 'failure')
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Post PR comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **CI checks failed**

            Please run locally and fix issues:
            ```bash
            npm run validate:all
            npm run test:visual
            npm run test:ci
            ```

