name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Lint, HTML validate, and unit tests
        run: npm run validate:all

  safari-tests:
    runs-on: macos-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright WebKit
        run: npx playwright install --with-deps webkit
      - name: Run core Safari scenarios
        run: npm run test:core
      - name: Run awareness mocks
        run: npm run test:awareness

  performance:
    runs-on: macos-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright WebKit
        run: npx playwright install --with-deps webkit
      - name: Run performance tests
        run: npm run test:performance
