name: Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Serve site and smoke test
        run: |
          python3 -m http.server 8000 & PID=$!
          sleep 1
          if curl -sSfI http://localhost:8000/wake.html >/dev/null; then
            echo "OK"
            kill $PID
          else
            kill $PID || true
            exit 1
          fi
